spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
error:
  webhook:
    url: ${DEV_WEBHOOK_URL}
cloud:
  naver:
    credentials:
      end-point: "https://kr.object.ncloudstorage.com"
      region: "kr-standard"
      access-key: ${OBJECT_STORAGE_ACCESS_KEY}
      secret-key: ${OBJECT_STORAGE_SECRET_KEY}
      bucket: "praise-up-image"